# Generated by Django 5.1 on 2024-09-02 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_rename_valor_usuario_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='cpf',
        ),
    ]
