# Generated by Django 5.1 on 2024-09-07 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0005_usuario_data_nascimento_alter_usuario_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.IntegerField(),
        ),
    ]
